name: Changelog
on:
  push:
    branches: [ main ]
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
