name: Release npm package

on:
  push:
    branches:
      - release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
      run: npx semantic-release