name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: npm ci
      - run: git config --global user.email "sawa.gawlau@gmail.com"
      - run: git config --global user.name "SawaGawlau"
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}