name: Release
on:
  push:
    branches:
      - test
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Start
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Release
        uses: cycjimmy/semantic-release-action@v4.0.0
    
    
